site_name: Introduction to OpenRefine
site_url: https://finnsdottir.github.io/openrefine_fall2025
theme:
  name: material
  palette:
    primary: indigo
  features:
  - navigation.sections
  - toc.integrate
  - navigation.top

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Introduction: index.md
  - Land Acknowledgement: land_acknowledgement.markdown
  - Getting started: starting.markdown
  - Facets: facets.markdown
  - Clustering: clusters.markdown
  - Filtering & sorting: filtering.markdown
  - Transformations: transformations.markdown
  - Working with numbers: numbers.markdown
  - Undo & redo: undo-redo.markdown
  - Saving your work: scripts.markdown

extra_css:
  - stylesheets/extra.css
